BLACK = (0, 0, 0)
RED = (15, 0, 0)
YELLOW = (15, 15, 0)
GREEN = (0, 15, 0)
CYAN = (0, 15, 15)
BLUE = (0, 0, 15)
PURPLE = (15, 0, 15)
WHITE = (15, 15, 15)

COLORS = [RED, YELLOW, GREEN, CYAN, BLUE, PURPLE, WHITE,BLACK ]

LATTICE = [CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN,
           CYAN, CYAN, RED, RED, CYAN, CYAN, RED, RED, RED, RED, CYAN, CYAN, CYAN, RED, RED, CYAN,
           CYAN, RED, RED, RED, CYAN, RED, CYAN, CYAN, CYAN, CYAN, RED, CYAN, RED, RED, RED, CYAN,
           CYAN, CYAN, RED, RED, CYAN, CYAN, CYAN, CYAN, CYAN, RED, RED, CYAN, CYAN, RED, RED, CYAN,
           CYAN, CYAN, RED, RED, CYAN, CYAN, CYAN, CYAN, RED, RED, CYAN, CYAN, CYAN, RED, RED, CYAN,
           CYAN, CYAN, RED, RED, CYAN, CYAN, CYAN, RED, RED, CYAN, CYAN, CYAN, CYAN, RED, RED, CYAN,
           CYAN, CYAN, RED, RED, CYAN, CYAN, RED, RED, CYAN, CYAN, CYAN, CYAN, CYAN, RED, RED, CYAN,
           CYAN, CYAN, RED, RED, CYAN, RED, RED, RED, RED, RED, RED, CYAN, CYAN, RED, RED, CYAN,
           CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN,
           CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN, CYAN]
        